spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  sql:
    init:
      encoding: utf-8
      mode: always
      schema-locations: classpath:h2/db_schema.sql
      data-locations: classpath:h2/data.sql

  logging:
    level:
      org:
        hibernate:
          type: trace

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
        format_sql: true